const actionTypes = {
  CREATE_CUSTOMER_SUCCESSFUL: 'CREATE-CUSTOMER_SUCCESSFUL',
  CREATE_CUSTOMER_FAILED: 'CREATE_CUSTOMER_FAILED',
  MAKE_PAYMENT_SUCCESSFUL: 'MAKE_PAYMENT_SUCCESSFUL',
  MAKE_PAYMENT_FAILED: 'MAKE_PAYMENT_FAILED',
  MAKING_PAYMENT: 'MAKING_PAYMENT',
  GET_TOKEN_SUCCESSFUL: 'GET_TOKEN_SUCCESSFUL',
  GET_TOKEN_FAILED: 'GET_TOKEN_FAILED',
  CREATE_CARD_SUCCESSFUL: 'CREATE_CARD_SUCCESSFUL',
  CREATE_CARD_FAILED: 'CREATE_CARD_FAILED',
  CREATING_CARD: 'CREATING_CARD',
  GET_CARDS_SUCCESSFUL: 'GET_CARDS_SUCCESSFUL',
  GET_CARDS_FAILED: 'GET_CARDS_FAILED'
};

export default actionTypes;
