const actionTypes = {
  CREATE_CUSTOMER_SUCCESSFUL: 'CREATE-CUSTOMER_SUCCESSFUL',
  CREATE_CUSTOMER_FAILED: 'CREATE_CUSTOMER_FAILED',
  MAKE_PAYMENT_SUCCESSFUL: 'MAKE_PAYMENT_SUCCESSFUL',
  MAKE_PAYMENT_FAILED: 'MAKE_PAYMENT_FAILED',
  CLEAR_PAYMENT_SUCCESS_FLAG: 'CLEAR_PAYMENT_SUCCESS_FLAG',
  GET_TOKEN_SUCCESSFUL: 'GET_TOKEN_SUCCESSFUL',
  GET_TOKEN_FAILED: 'GET_TOKEN_FAILED',
  CLEAR_TOKEN_SUCCESS_FLAG: 'CLEAR_TOKEN_SUCCESS_FLAG',
  CREATE_CARD_SUCCESSFUL: 'CREATE_CARD_SUCCESSFUL',
  CREATE_CARD_FAILED: 'CREATE_CARD_FAILED',
  DELETE_CARD_SUCCESSFUL: 'DELETE_CARD_SUCCESSFUL',
  DELETE_CARD_FAILED: 'DELETE_CARD_FAILED'
};

export default actionTypes;
