const responseType = {
  CREATE_CUSTOMER_SUCCESSFUL: 1,
  CREATE_CUSTOMER_FAILED: 2,
  MAKE_PAYMENT_SUCCESSFUL: 3,
  MAKE_PAYMENT_FAILED: 4,
  GET_TOKEN_SUCCESSFUL: 5,
  GET_TOKEN_FAILED: 6,
  CREATE_CARD_SUCCESSFUL: 7,
  CREATE_CARD_FAILED: 8,
  GET_CARDS_SUCCESSFUL: 9,
  GET_CARDS_FAILED: 10
};

export default responseType;
